### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: 

### ISSUE THREAD

**Issue by julioflima** [words/dice-coefficient#21]
Maybe this is just a webpack 4 problem, but I'm removing to use the natural package, even being not so good on the benchmark.

I was using typescript.

Tested in nodes:
v10.21.0
v12.22.1
v14.17.0

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/julio/projects/node_modules/dice-coefficient/index.js
require() of ES modules is not supported.
require() of /home/julio/projects/node_modules/dice-coefficient/index.js from /home/julio/projects/.next/server/pages/_document.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/julio/projects/node_modules/dice-coefficient/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack-internal:///dice-coefficient:1:18)
    at Object.dice-coefficient (/home/julio/projects/.next/server/pages/_document.js:547:1)
    at __webpack_require__ (/home/julio/projects/.next/server/pages/_document.js:23:31)
    at eval (webpack-internal:///./src/factory/TextFactory/index.ts:3:74)
    at Module../src/factory/TextFactory/index.ts (/home/julio/projects/.next/server/pages/_document.js:356:1)
    at __webpack_require__ (/home/julio/projects/.next/server/pages/_document.js:23:31)
    at eval (webpack-internal:///./src/factory/index.ts:8:70)
    at Module../src/factory/index.ts (/home/julio/projects/.next/server/pages/_document.js:368:1)
    at __webpack_require__ (/home/julio/projects/.next/server/pages/_document.js:23:31)
    at eval (webpack-internal:///./src/provider/TextProvider/index.ts:3:66)
    at Module../src/provider/TextProvider/index.ts (/home/julio/projects/.next/server/pages/_document.js:452:1) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by wooorm** [comment]
Esm is inteded

**Comment by sdegutis** [comment]
Is there any way you can convert this to use `module.exports` until ESM is no longer "experimental but without flags or even warnings for some reason 😕 " in Node.js? Then both ESM and CJS apps can import and use this (and n-gram which this uses). Otherwise, only ESM apps can. Once ESM support is no longer in that weird state, more apps will probably be able/willing to use `"type": "module"` in their package.json, but until then, ESM-only limit who can use this.

**Comment by sdegutis** [comment]
For context, I recently switched an app away from ESM to CJS to avoid some configuration complexities with using various libs together, since not everything supports ESM very well. And in order to use this library, I literally had to inline its source into that project, and include the MIT licenses in the files (this and n-gram). I'd like to remove that from the repo, it doesn't really belong there. But I can't unless you convert this to CommonJS.

**Comment by wooorm** [comment]
[ESM is stable](https://nodejs.org/api/esm.html). You can use a dynamic import expression to import this package from CJS. You can also use the previous version. Or switch to ESM, which I strongly recommend. See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c for more on the options you have.

**Comment by sdegutis** [comment]
ESM may be stable, but ESM Loaders are still experimental, hence https://github.com/TypeStrong/ts-node/issues/1007. And Node usage isn't just Node.js itself but also the ecosystem, including ts-node.

**Comment by wooorm** [comment]
The alternative to loaders (require hooks) is deprecated.
You‘re stuck between a rock and a hard place.
Please also note that a lot has happened in that project since the issue was raised 19 months ago.

This is not the place to ask questions about how to use ESM or what alternatives there are (again: use the last version). This is also not a place for discussions about when the right time is.

ESM is the future. This is free software. I gave 6 months of my finite life to updating everything. You might’ve liked it if it was next month. I disagree. But it’s not going to change.

Use the previous version, switch to ESM, bundle, vendor, or use ESM from within CJS.
